# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from draw import Draw
from algorithms import * 

def resource_path(relative_path):
    #Relative path for icons
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 1015)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(parent=self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuClear = QtWidgets.QMenu(parent=self.menubar)
        self.menuClear.setObjectName("menuClear")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("icons/open_file.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("icons/exit.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_DT = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("icons/triangles2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreate_DT.setIcon(icon2)
        self.actionCreate_DT.setObjectName("actionCreate_DT")
        self.actionCreateContouLines = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("icons/contours2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreateContouLines.setIcon(icon3)
        self.actionCreateContouLines.setObjectName("actionCreateContouLines")
        self.actionAnalyzeSlope = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("icons/slope2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeSlope.setIcon(icon4)
        self.actionAnalyzeSlope.setObjectName("actionAnalyzeSlope")
        self.actionAnalyzeExposition = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(resource_path("icons/orientation2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeExposition.setIcon(icon5)
        self.actionAnalyzeExposition.setObjectName("actionAnalyzeExposition")
        self.actionDT = QtGui.QAction(parent=MainWindow)
        self.actionDT.setCheckable(True)
        self.actionDT.setObjectName("actionDT")
        self.actionContour_lines_2 = QtGui.QAction(parent=MainWindow)
        self.actionContour_lines_2.setCheckable(True)
        self.actionContour_lines_2.setObjectName("actionContour_lines_2")
        self.actionSlope = QtGui.QAction(parent=MainWindow)
        self.actionSlope.setCheckable(True)
        self.actionSlope.setObjectName("actionSlope")
        self.actionExposition = QtGui.QAction(parent=MainWindow)
        self.actionExposition.setCheckable(True)
        self.actionExposition.setObjectName("actionExposition")
        self.actionClear_results = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(resource_path("icons/clear.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon6)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(resource_path("icons/clear_all.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon7)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionParameters = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(resource_path("icons/settings.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionParameters.setIcon(icon8)
        self.actionParameters.setObjectName("actionParameters")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAnalysis.addAction(self.actionCreate_DT)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionCreateContouLines)
        self.menuAnalysis.addAction(self.actionAnalyzeSlope)
        self.menuAnalysis.addAction(self.actionAnalyzeExposition)
        self.menuView.addAction(self.actionDT)
        self.menuView.addAction(self.actionContour_lines_2)
        self.menuView.addAction(self.actionSlope)
        self.menuView.addAction(self.actionExposition)
        self.menuClear.addAction(self.actionClear_results)
        self.menuClear.addSeparator()
        self.menuClear.addAction(self.actionClear_all)
        self.menuSettings.addAction(self.actionParameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_DT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreateContouLines)
        self.toolBar.addAction(self.actionAnalyzeSlope)
        self.toolBar.addAction(self.actionAnalyzeExposition)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        
        #Connects - Analysis
        self.actionCreate_DT.triggered.connect(self.createDTClick)
        self.actionCreateContouLines.triggered.connect(self.createContourLinesClick)
        self.actionAnalyzeSlope.triggered.connect(self.analyzeSlopeClick)
        self.actionAnalyzeExposition.triggered.connect(self.analyzeExpositionClick)

        #Connects - File
        self.actionOpen.triggered.connect(self.openFileClick)
        self.actionExit.triggered.connect(QtWidgets.QApplication.quit)

        #Connects - Clear
        self.actionClear_results.triggered.connect(self.clearResultClick)
        self.actionClear_all.triggered.connect(self.clearAllClick)

        #Connects - View (layers visibility)
        #Set all view actions checked by default (all layers visible)
        self.actionDT.setChecked(True)
        self.actionContour_lines_2.setChecked(True)
        self.actionSlope.setChecked(True)
        self.actionExposition.setChecked(True)

        self.actionDT.triggered.connect(self.toggleDT)
        self.actionContour_lines_2.triggered.connect(self.toggleContours)
        self.actionSlope.triggered.connect(self.toggleSlope)
        self.actionExposition.triggered.connect(self.toggleExposition)

        self.retranslateUi(MainWindow)
        

    #User defined function
    def createDTClick(self):
        #Create DT
        
        #Get points
        points = self.Canvas.getPoints()
        
        #Create new object
        a = Algorithms()
        
        #Process data> create DT
        dt = a.createDT(points)
        
        #Set results
        self.Canvas.setDT(dt)
        
        #Repaint
        self.Canvas.repaint()
        
        
    def createContourLinesClick(self):
        #Create contour lines
        DT = self.Canvas.getDT()
        
        #We need to create DT
        if len(DT) <3:
            
            #Generate DT
            self.createDTClick()
            
            #Get DT
            DT = self.Canvas.getDT()
        
        #Get z range from actual points (not hardcoded!)
        points = self.Canvas.getPoints()
        z_values = [p.z() for p in points]
        z_min = int(min(z_values))
        z_max = int(max(z_values)) + 1

        #Contour interval: ~20 contour lines across the range
        dz = max(1, (z_max - z_min) // 20)

        #Main contour interval (every 5th contour is highlighted)
        dz_main = dz * 5

        #Create contour lines
        a = Algorithms()
        contours = a.createContourLines(DT, z_min, z_max, dz)
        main_contours = a.createContourLines(DT, z_min, z_max, dz_main)

        #Set results
        self.Canvas.setContours(contours)
        self.Canvas.setMainContours(main_contours)
        
        #Repaint
        self.Canvas.repaint()


    def analyzeSlopeClick(self):
        #Analyze slope of each triangle in DT
        DT = self.Canvas.getDT()

        #We need to create DT first
        if len(DT) < 3:
            self.createDTClick()
            DT = self.Canvas.getDT()

        #Compute slope for all triangles
        a = Algorithms()
        slope_triangles = a.analyzeSlope(DT)

        #Set results and repaint
        self.Canvas.setSlopeTriangles(slope_triangles)
        self.Canvas.repaint()


    def analyzeExpositionClick(self):
        #Analyze aspect (exposition) of each triangle in DT
        DT = self.Canvas.getDT()

        #We need to create DT first
        if len(DT) < 3:
            self.createDTClick()
            DT = self.Canvas.getDT()

        #Compute aspect for all triangles
        a = Algorithms()
        aspect_triangles = a.analyzeAspect(DT)

        #Set results and repaint
        self.Canvas.setAspectTriangles(aspect_triangles)
        self.Canvas.repaint()

        

    def openFileClick(self):
        #Open txt file and load points
        
        #Open file dialog
        file_path = QtWidgets.QFileDialog.getOpenFileName(
            None, "Open file", "", "Text files (*.txt);;All files (*)"
        )[0]
        
        #No file selected
        if not file_path:
            return
        
        #Read points from file
        points_raw = []
        
        try:
            with open(file_path, "r") as f:
                for line in f:
                    #Skip empty lines and comment lines
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    
                    #Split line into values
                    parts = line.split()
                    
                    #Need at least x, y, z
                    if len(parts) < 3:
                        continue
                    
                    #Parse x, y, z coordinates
                    x = float(parts[0])
                    y = float(parts[1])
                    z = float(parts[2])
                    
                    points_raw.append((x, y, z))
                    
        except Exception as e:
            QtWidgets.QMessageBox.warning(None, "Error", "Could not read file:\n" + str(e))
            return
        
        #Check we have some points
        if len(points_raw) < 3:
            QtWidgets.QMessageBox.warning(None, "Error", "File must contain at least 3 points.")
            return
        
        #Scale x, y coordinates to fit canvas size
        #Get canvas dimensions
        canvas_w = self.Canvas.width()
        canvas_h = self.Canvas.height()
        margin = 50
        
        #Find min and max of x and y in file
        x_min = min(p[0] for p in points_raw)
        x_max = max(p[0] for p in points_raw)
        y_min = min(p[1] for p in points_raw)
        y_max = max(p[1] for p in points_raw)
        
        #Avoid division by zero if all points on same x or y
        dx = x_max - x_min if x_max != x_min else 1
        dy = y_max - y_min if y_max != y_min else 1
        
        #Create scaled QPoint3DF points
        points = []
        for (x, y, z) in points_raw:
            #Scale to canvas with margin
            #Y is flipped: y_max -> top (margin), y_min -> bottom (canvas_h - margin)
            xs = (x - x_min) / dx * (canvas_w - 2 * margin) + margin
            ys = (y_max - y) / dy * (canvas_h - 2 * margin) + margin
            
            p = QPoint3DF(xs, ys, z)
            points.append(p)
        
        #Clear old data and set new points
        self.Canvas.clearResult()
        self.Canvas.setPoints(points)
        self.Canvas.setFileLoaded(True)   #Disable adding points by mouse click
        
        #Repaint
        self.Canvas.repaint()


    def clearResultClick(self):
        #Clear analysis results, keep points
        self.Canvas.clearResult()


    def clearAllClick(self):
        #Clear everything including points
        self.Canvas.clearAll()

        #Reset view checkboxes to checked (all visible by default)
        self.actionDT.setChecked(True)
        self.actionContour_lines_2.setChecked(True)
        self.actionSlope.setChecked(True)
        self.actionExposition.setChecked(True)


    def toggleDT(self):
        #Toggle DT layer visibility
        self.Canvas.setShowDT(self.actionDT.isChecked())


    def toggleContours(self):
        #Toggle contour lines layer visibility
        self.Canvas.setShowContours(self.actionContour_lines_2.isChecked())


    def toggleSlope(self):
        #Toggle slope layer visibility
        self.Canvas.setShowSlope(self.actionSlope.isChecked())


    def toggleExposition(self):
        #Toggle aspect (exposition) layer visibility
        self.Canvas.setShowAspect(self.actionExposition.isChecked())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTM Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open file"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Backspace"))
        self.actionCreate_DT.setText(_translate("MainWindow", "Create DT"))
        self.actionCreate_DT.setToolTip(_translate("MainWindow", "Create Delaunay triangulation"))
        self.actionCreateContouLines.setText(_translate("MainWindow", "Create contour lines"))
        self.actionAnalyzeSlope.setText(_translate("MainWindow", "Analyze slope"))
        self.actionAnalyzeSlope.setToolTip(_translate("MainWindow", "Analyze DTM slope"))
        self.actionAnalyzeExposition.setText(_translate("MainWindow", "Analyze exposition"))
        self.actionAnalyzeExposition.setToolTip(_translate("MainWindow", "Analyze DTM exposition"))
        self.actionDT.setText(_translate("MainWindow", "DT"))
        self.actionContour_lines_2.setText(_translate("MainWindow", "Contour lines"))
        self.actionSlope.setText(_translate("MainWindow", "Slope"))
        self.actionExposition.setText(_translate("MainWindow", "Exposition"))
        self.actionClear_results.setText(_translate("MainWindow", "Clear results"))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all"))
from draw import Draw

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())